### ISSUE TITLE
Identify datasets by their IRI rather than identifier

### ISSUE THREAD

**Issue by ddeboer** [netwerk-digitaal-erfgoed/network-of-terms-comunica#17]
The dataset identifiers that we now use are made-up (albeit common) abbreviations of dataset names, for instance ‘rkdartists’ and ‘cht’. Should we replace these identifiers with proper IRIs?

Some considerations:

- Short strings like our current identifiers look more familiar to GraphQL users than IRIs.
- When the number of term sources grows, identifier collisions become more likely, especially if they are provided by term source managers themselves rather than NDE.
- IRIs can be resolved for further information about the dataset, whereas identifiers are a dead end.

@sdevalk Should we allow identification _only_ by IRI or also keep supporting the identifiers?

**Comment by sdevalk** [comment]
My proposal would be to only allow URIs:

1. We don't have to maintain a list of identifiers/abbreviations anymore (we can use whatever the data source provides).
2. We become a bit more opinionated for simplicity's sake ('URIs, not URIs or abbreviations').

Follow-up question: which URI should we use as identifier? The URI of a dataset or the URI of a distribution?

Most user applications are probably only interested in the data and they want the Network of Terms to use a data source that gives the best and fastest answers (e.g. the SPARQL endpoint distribution). However, perhaps a user application deliberately wants to use a specific distribution of a data source (e.g. a TPF endpoint, backed by a HDT) because it fits their implementation (e.g. they're not interested in the fastest distribution).

**Comment by ddeboer** [comment]
Agreed, let’s use IRIs only.

> Follow-up question: what URI should we use as identifier? The URI of a dataset or the URI of a distribution?

Along the same lines (simplicity), let’s use the dataset (source) URI. This gives the Network of Terms some flexibility in swapping endpoints for technical reasons (as long as they provide they same dataset).

> because it fits their implementation (e.g. they're not interested in the fastest distribution).

I don’t think regular users should care about the implementation because they will use one of the implementations provided by NDE: either the GraphQL abstraction or the client-side Comunica wrapper. 

Power users can query Comunica (or any other query engine) directly with the distribution URIs. These URIs then should still be available from the catalog.

**Comment by sdevalk** [comment]
> I don’t think regular users should care about the implementation because they will use one of the implementations provided by NDE: either the GraphQL abstraction or the client-side Comunica wrapper.
> 
> Power users can query Comunica (or any other query engine) directly with the distribution URIs. These URIs then should still be available in the catalog data.

Yes, this makes sense. In other words:

1. The administrator of (an instance of) the NoT decides what terminology sources (a.k.a. datasets) can be queried via the NoT. The administrator also decides what distribution of each terminology source is used (e.g. the SPARQL endpoint, not the TPF endpoint). The administrator can only choose *one* distribution, not multiple, because users (e.g. cultural heritage institutions and their IT vendors) in most cases don't care about the distributions - they want the administrator to choose the best one.

2. If, however, a user wants to use a different distribution of a terminology source than the one chosen by the administrator (e.g. the TPF endpoint, not the SPARQL endpoint), the user can either deploy his own instance of the NoT with a specific configuration or configure his query client - such as Comunica - to use a specific distribution.

To explore the consequences of this direction:

Suppose the administrator decides to use the 'SPARQL endpoint distribution' of terminology source X. Later on a new distribution of this source becomes available: a 'Web API distribution'. This distribution offers better performance than the SPARQL endpoint. The administrator therefore decides to use this new distribution in his configuration of the NoT. Users/user applications won't notice this change: the way they query the source - via the NoT interfaces - stays the same. However, suppose that this new distribution returns its results a bit different than the 'SPARQL endpoint distribution' (e.g. due to a new form of relevance ranking). Certain users may not agree with this change and prefer the old distribution.

How should we handle this? For example: should the administrator not simply change the distributions in the configuration but first deploy the new configuration to a staging environment for testing by users? Or should we - in the NoT - support multiple distributions per terminology source after all (so that the administrator can offer one or more distributions and users can decide which one they prefer)?

@EnnoMeijers What are your thoughts?

**Comment by EnnoMeijers** [comment]
I think we should aim for maximum flexibility, so we should support multiple distributions per terminology source. In general formal NoT instances with a large user base should always have a decent processes for handling updates (including a staging environment). Advanced user groups can run their own implementation and select their preferred distributions. The NoT should not be restrictive in both use cases.

**Comment by sdevalk** [comment]
@EnnoMeijers Thanks! We'll continue our work in this direction then:

1. The NoT supports multiple distributions per terminology source (e.g. a SPARQL endpoint *and* a TPF endpoint)
2. A 'source' in the NoT is identified by its IRI (not by an abbreviation, as is currently the case). The IRI identifies a specific distribution (not the dataset to which the distribution belongs)
