### ISSUE TITLE
Empty resultset for CHT query

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/network-of-terms-comunica#19]
See the first example query in the README.md: 
# Cultuurhistorische Thesaurus: query SPARQL endpoint
bin/run sources:query --identifiers cht --query fiets

This query returns an empty result set, it should list multiple terms containing 'fiets'. 
I tested the query from the catalog direct on the CHT endpoint (https://digitaalerfgoed.poolparty.biz/PoolParty/sparql/term/id/cht) that worked fine.

**Comment by sdevalk** [comment]
This, unfortunately, is caused by a fix that we've applied recently in order to fix [this issue](https://github.com/netwerk-digitaal-erfgoed/network-of-terms-comunica/issues/11). I've reported similar problems with queries in [this issue](https://github.com/netwerk-digitaal-erfgoed/network-of-terms-comunica/issues/14).

The core issue is that we need to find a way to handle query differences between SPARQL endpoints: the current 'one size fits all' implementation doesn't suffice (i.e. it doesn't fit all).
